###
GET http://localhost:7000/auth


###
POST https://simple-log-eta.vercel.app/auth
content-type: application/json

{
    "name": "nisa",
    "password": "jajan"
}

###
POST http://localhost:7000/auth/login
content-type: application/json

{
    "name": "mana",
    "password": "telkomsel"
}