###
GET http://localhost:7000/auth


###
POST http://localhost:7000/auth/register
content-type: application/json

{
    "name": "maahhh",
    "password": "lkomsel"
}

###
POST http://localhost:7000/auth/login
content-type: application/json

{
    "name": "nisa",
    "password": "jajan"
}
  
###
GET http://localhost:7000/auth/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJuaXNhIn0sImlhdCI6MTcwNTEwODU5OCwiZXhwIjoxNzA1MTEyMTk4fQ.KrUjiY3XxLpE4VY118xgd621D6Mx4Z_evBCKX6ep-8s


###
POST http://localhost:7000/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJuaXNhIn0sImlhdCI6MTcwNTEwODU5OCwiZXhwIjoxNzA1MTEyMTk4fQ.KrUjiY3XxLpE4VY118xgd621D6Mx4Z_evBCKX6ep-8s


###
GET http://localhost:7000/auth/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJuaXNhIn0sImlhdCI6MTcwNTEwODU5OCwiZXhwIjoxNzA1MTEyMTk4fQ.KrUjiY3XxLpE4VY118xgd621D6Mx4Z_evBCKX6ep-8s
